### ISSUE TITLE
Oracle driver

### ISSUE THREAD

**Issue by student2ua** [student2ua/RESTserv#1]
DB -oracle 9i
**classes12.jar** - 
INFO  Exposed - Transaction attempt #0 failed: Действительны только уровни транзакций READ_COMMITTED и SERIALIZABLE. Statement(s): null
java.sql.SQLException: Действительны только уровни транзакций READ_COMMITTED и SERIALIZABLE
	at oracle.jdbc.dbaccess.DBError.throwSqlException(DBError.java:134)
	at oracle.jdbc.dbaccess.DBError.throwSqlException(DBError.java:179)
	at oracle.jdbc.dbaccess.DBError.throwSqlException(DBError.java:269)
	at oracle.jdbc.driver.OracleConnection.setTransactionIsolation(OracleConnection.java:1645)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction$connectionLazy$1.invoke(ThreadLocalTransactionManager.kt:27)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction$connectionLazy$1.invoke(ThreadLocalTransactionManager.kt:22)
	at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction.getConnection(ThreadLocalTransactionManager.kt:31)
	at org.jetbrains.exposed.sql.Transaction.getConnection(Transaction.kt)
	at org.jetbrains.exposed.sql.Database.getMetadata$exposed(Database.kt:17)
	at org.jetbrains.exposed.sql.Database$url$2.invoke(Database.kt:26)
	at org.jetbrains.exposed.sql.Database$url$2.invoke(Database.kt:15)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.exposed.sql.Database.getUrl(Database.kt)
	at org.jetbrains.exposed.sql.Database$dialect$2.invoke(Database.kt:29)
	at org.jetbrains.exposed.sql.Database$dialect$2.invoke(Database.kt:15)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.exposed.sql.Database.getDialect$exposed(Database.kt)
	at org.jetbrains.exposed.sql.vendors.DefaultKt.getCurrentDialect(Default.kt:341)
	at org.jetbrains.exposed.sql.vendors.DefaultKt.getCurrentDialectIfAvailable(Default.kt:345)
	at org.jetbrains.exposed.sql.vendors.DefaultKt.inProperCase(Default.kt:348)
	at org.jetbrains.exposed.sql.Transaction.fullIdentity(Transaction.kt:168)
	at org.jetbrains.exposed.sql.Column.toSQL(Column.kt:31)
	at org.jetbrains.exposed.sql.Query$prepareSQL$$inlined$buildString$lambda$1.invoke(Query.kt:156)
	at org.jetbrains.exposed.sql.Query$prepareSQL$$inlined$buildString$lambda$1.invoke(Query.kt:82)
	at kotlin.text.StringsKt__StringBuilderKt.appendElement(StringBuilder.kt:58)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:2195)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:2212)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:2211)
	at org.jetbrains.exposed.sql.Query.prepareSQL(Query.kt:156)
	at org.jetbrains.exposed.sql.Query.arguments(Query.kt:140)
	at org.jetbrains.exposed.sql.Query.arguments(Query.kt:82)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:32)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:128)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:122)
	at org.jetbrains.exposed.sql.Query.iterator(Query.kt:285)
	at com.ua.ecwo.repos.IKTRepoImpl_asSample$listAll$2.invoke(IKTRepoImpl.kt:53)
	at com.ua.ecwo.repos.IKTRepoImpl_asSample$listAll$2.invoke(IKTRepoImpl.kt:8)
	at com.ua.ecwo.repos.DatabaseFactory$dbQuery$2$1.invoke(DatabaseFactory.kt:56)
	at com.ua.ecwo.repos.DatabaseFactory$dbQuery$2$1.invoke(DatabaseFactory.kt:14)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:103)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:74)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:57)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:57)
	at com.ua.ecwo.repos.DatabaseFactory$dbQuery$2.doResume(DatabaseFactory.kt:53)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:149)
	at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by student2ua** [comment]
**transaction(java.sql.Connection.TRANSACTION_READ_COMMITTED, 3)**

2018-10-23 16:59:47.199 [database-pool-1] DEBUG Exposed - SELECT DCT_LOCAL.IKT_ELECTRONIC_COURSES.ID, DCT_LOCAL.IKT_ELECTRONIC_COURSES.NAME, DCT_LOCAL.IKT_ELECTRONIC_COURSES.SHORTNAME, DCT_LOCAL.IKT_ELECTRONIC_COURSES.DEPARTMENT_ID FROM DCT_LOCAL.IKT_ELECTRONIC_COURSES
SQL: SELECT DCT_LOCAL.IKT_ELECTRONIC_COURSES.ID, DCT_LOCAL.IKT_ELECTRONIC_COURSES.NAME, DCT_LOCAL.IKT_ELECTRONIC_COURSES.SHORTNAME, DCT_LOCAL.IKT_ELECTRONIC_COURSES.DEPARTMENT_ID FROM DCT_LOCAL.IKT_ELECTRONIC_COURSES
2018-10-23 16:59:47.203 [database-pool-1] INFO  Exposed - Transaction attempt #0 failed: ### **### java.sql.SQLException: Не поддерживаемая функция**. Statement(s): SELECT DCT_LOCAL.IKT_ELECTRONIC_COURSES.ID, DCT_LOCAL.IKT_ELECTRONIC_COURSES.NAME, DCT_LOCAL.IKT_ELECTRONIC_COURSES.SHORTNAME, DCT_LOCAL.IKT_ELECTRONIC_COURSES.DEPARTMENT_ID FROM DCT_LOCAL.IKT_ELECTRONIC_COURSES
org.jetbrains.exposed.exceptions.ExposedSQLException: java.sql.SQLException: Не поддерживаемая функция
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:48)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:128)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:122)
	at org.jetbrains.exposed.sql.Query.iterator(Query.kt:285)
	at com.ua.ecwo.repos.IKTRepoImpl_asSample$listAll$2.invoke(IKTRepoImpl.kt:53)
	at com.ua.ecwo.repos.IKTRepoImpl_asSample$listAll$2.invoke(IKTRepoImpl.kt:8)
	at com.ua.ecwo.repos.DatabaseFactory$dbQuery$2$1.invoke(DatabaseFactory.kt:56)
	at com.ua.ecwo.repos.DatabaseFactory$dbQuery$2$1.invoke(DatabaseFactory.kt:14)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:103)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:74)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:59)
	at com.ua.ecwo.repos.DatabaseFactory$dbQuery$2.doResume(DatabaseFactory.kt:52)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:149)
	at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: Не поддерживаемая функция
	at oracle.jdbc.dbaccess.DBError.throwSqlException(DBError.java:134)
	at oracle.jdbc.dbaccess.DBError.throwSqlException(DBError.java:179)
	at oracle.jdbc.dbaccess.DBError.throwSqlException(DBError.java:269)
	at oracle.jdbc.dbaccess.DBError.throwUnsupportedFeatureSqlException(DBError.java:689)
	at oracle.jdbc.driver.OracleConnection.prepareStatement(OracleConnection.java:3360)
	at org.jetbrains.exposed.sql.statements.Statement.prepared(Statement.kt:25)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:46)
	... 21 common frames omitted

**Comment by student2ua** [comment]
**ojdbc14-9.2.0.5.jar** ( old Oracle 9.2 JDBC driver  does not use ALTER SESSION SET NLS_LANGUAGE commands)
2018-10-23 17:49:43.559 [database-pool-1] INFO  Exposed - Transaction attempt #0 failed: java.sql.SQLException: Не поддерживаемая функция. Statement(s): SELECT DCT_LOCAL.IKT_ELECTRONIC_COURSES.ID, DCT_LOCAL.IKT_ELECTRONIC_COURSES.NAME, DCT_LOCAL.IKT_ELECTRONIC_COURSES.SHORTNAME, DCT_LOCAL.IKT_ELECTRONIC_COURSES.DEPARTMENT_ID FROM DCT_LOCAL.IKT_ELECTRONIC_COURSES
org.jetbrains.exposed.exceptions.ExposedSQLException: java.sql.SQLException: Не поддерживаемая функция
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:48)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:128)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:122)
	at org.jetbrains.exposed.sql.Query.iterator(Query.kt:285)
	at com.ua.ecwo.repos.IKTRepoImpl_asSample$listAll$2.invoke(IKTRepoImpl.kt:53)
	at com.ua.ecwo.repos.IKTRepoImpl_asSample$listAll$2.invoke(IKTRepoImpl.kt:8)
	at com.ua.ecwo.repos.DatabaseFactory$dbQuery$2$1.invoke(DatabaseFactory.kt:56)
	at com.ua.ecwo.repos.DatabaseFactory$dbQuery$2$1.invoke(DatabaseFactory.kt:14)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:103)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:74)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:59)
	at com.ua.ecwo.repos.DatabaseFactory$dbQuery$2.doResume(DatabaseFactory.kt:52)

**Comment by student2ua** [comment]
**ojdbc14-10.2.0.4.0**
2018-10-23 19:07:23.913 [nettyCallPool-4-1] ERROR Application - Unhandled: GET - /papi/ikt/electroniccourses
java.lang.AbstractMethodError: Method oracle/jdbc/driver/T4CPreparedStatement.isClosed()Z is abstract
	at oracle.jdbc.driver.T4CPreparedStatement.isClosed(T4CPreparedStatement.java)
	at org.jetbrains.exposed.sql.Transaction.closeExecutedStatements(Transaction.kt:179)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:136)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:74)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:59)
	at com.ua.ecwo.repos.DatabaseFactory$dbQuery$2.doResume(DatabaseFactory.kt:52)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:149)
	at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by student2ua** [comment]
**ojdbc6.jar+orai18n.jar ver 12.1.0.1.0**
2018-10-23 20:44:07.774 [database-pool-1] INFO  Exposed - Transaction attempt #0 failed: ORA-00604: error occurred at recursive SQL level 1
**ORA-01882**: timezone region  not found
. Statement(s): null
java.sql.SQLException: ORA-00604: error occurred at recursive SQL level 1
ORA-01882: timezone region  not found

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:392)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:385)
	at oracle.jdbc.driver.T4CTTIfun.processError(T4CTTIfun.java:938)
	at oracle.jdbc.driver.T4CTTIoauthenticate.processError(T4CTTIoauthenticate.java:476)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:655)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:249)
	at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:412)
	at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:821)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:596)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:711)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:385)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:30)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:558)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at org.jetbrains.exposed.sql.Database$Companion$connect$7.invoke(Database.kt:112)
	at org.jetbrains.exposed.sql.Database$Companion$connect$7.invoke(Database.kt:71)
	at org.jetbrains.exposed.sql.Database$Companion$doConnect$3.invoke(Database.kt:91)
	at org.jetbrains.exposed.sql.Database$Companion$doConnect$3.invoke(Database.kt:71)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction$connectionLazy$1.invoke(ThreadLocalTransactionManager.kt:25)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction$connectionLazy$1.invoke(ThreadLocalTransactionManager.kt:22)
	at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction.getConnection(ThreadLocalTransactionManager.kt:31)
	at org.jetbrains.exposed.sql.Transaction.getConnection(Transaction.kt)
	at org.jetbrains.exposed.sql.Database.getMetadata$exposed(Database.kt:17)
	at org.jetbrains.exposed.sql.Database$url$2.invoke(Database.kt:26)
	at org.jetbrains.exposed.sql.Database$url$2.invoke(Database.kt:15)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.exposed.sql.Database.getUrl(Database.kt)
	at org.jetbrains.exposed.sql.Database$dialect$2.invoke(Database.kt:29)
	at org.jetbrains.exposed.sql.Database$dialect$2.invoke(Database.kt:15)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.exposed.sql.Database.getDialect$exposed(Database.kt)
	at org.jetbrains.exposed.sql.vendors.DefaultKt.getCurrentDialect(Default.kt:341)
	at org.jetbrains.exposed.sql.vendors.DefaultKt.getCurrentDialectIfAvailable(Default.kt:345)
	at org.jetbrains.exposed.sql.vendors.DefaultKt.inProperCase(Default.kt:348)
	at org.jetbrains.exposed.sql.Transaction.fullIdentity(Transaction.kt:168)
	at org.jetbrains.exposed.sql.Column.toSQL(Column.kt:31)
	at org.jetbrains.exposed.sql.Query$prepareSQL$$inlined$buildString$lambda$1.invoke(Query.kt:156)
	at org.jetbrains.exposed.sql.Query$prepareSQL$$inlined$buildString$lambda$1.invoke(Query.kt:82)
	at kotlin.text.StringsKt__StringBuilderKt.appendElement(StringBuilder.kt:58)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:2195)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:2212)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:2211)
	at org.jetbrains.exposed.sql.Query.prepareSQL(Query.kt:156)
	at org.jetbrains.exposed.sql.Query.arguments(Query.kt:140)
	at org.jetbrains.exposed.sql.Query.arguments(Query.kt:82)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:32)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:128)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:122)
	at org.jetbrains.exposed.sql.Query.iterator(Query.kt:285)
	at com.ua.ecwo.repos.IKTRepoImpl_asSample$listAll$2.invoke(IKTRepoImpl.kt:53)
	at com.ua.ecwo.repos.IKTRepoImpl_asSample$listAll$2.invoke(IKTRepoImpl.kt:8)
	at com.ua.ecwo.repos.DatabaseFactory$dbQuery$2$1.invoke(DatabaseFactory.kt:56)
	at com.ua.ecwo.repos.DatabaseFactory$dbQuery$2$1.invoke(DatabaseFactory.kt:14)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:103)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:74)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:59)
	at com.ua.ecwo.repos.DatabaseFactory$dbQuery$2.doResume(DatabaseFactory.kt:52)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:149)
	at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by student2ua** [comment]
**ojdbc8_g.jar**
2018-10-23 21:27:44.098 [database-pool-1] INFO  Exposed - Transaction attempt #0 failed: ORA-00604: error occurred at recursive SQL level 1
ORA-01882: timezone region  not found
. Statement(s): null
java.sql.SQLException: ORA-00604: error occurred at recursive SQL level 1
ORA-01882: timezone region  not found

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:490)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:437)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:432)
	at oracle.jdbc.driver.T4CTTIfun.processError(T4CTTIfun.java:1057)
	at oracle.jdbc.driver.T4CTTIoauthenticate.processError(T4CTTIoauthenticate.java:546)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:619)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:248)
	at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:495)
	at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:1318)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:659)
	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:684)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:35)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:687)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at org.jetbrains.exposed.sql.Database$Companion$connect$7.invoke(Database.kt:112)
	at org.jetbrains.exposed.sql.Database$Companion$connect$7.invoke(Database.kt:71)
	at org.jetbrains.exposed.sql.Database$Companion$doConnect$3.invoke(Database.kt:91)
	at org.jetbrains.exposed.sql.Database$Companion$doConnect$3.invoke(Database.kt:71)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction$connectionLazy$1.invoke(ThreadLocalTransactionManager.kt:25)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction$connectionLazy$1.invoke(ThreadLocalTransactionManager.kt:22)
	at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction.getConnection(ThreadLocalTransactionManager.kt:31)
	at org.jetbrains.exposed.sql.Transaction.getConnection(Transaction.kt)
	at org.jetbrains.exposed.sql.Database.getMetadata$exposed(Database.kt:17)
	at org.jetbrains.exposed.sql.Database$url$2.invoke(Database.kt:26)
	at org.jetbrains.exposed.sql.Database$url$2.invoke(Database.kt:15)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.exposed.sql.Database.getUrl(Database.kt)
	at org.jetbrains.exposed.sql.Database$dialect$2.invoke(Database.kt:29)
	at org.jetbrains.exposed.sql.Database$dialect$2.invoke(Database.kt:15)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.exposed.sql.Database.getDialect$exposed(Database.kt)
	at org.jetbrains.exposed.sql.vendors.DefaultKt.getCurrentDialect(Default.kt:341)
	at org.jetbrains.exposed.sql.vendors.DefaultKt.getCurrentDialectIfAvailable(Default.kt:345)
	at org.jetbrains.exposed.sql.vendors.DefaultKt.inProperCase(Default.kt:348)
	at org.jetbrains.exposed.sql.Transaction.fullIdentity(Transaction.kt:168)
	at org.jetbrains.exposed.sql.Column.toSQL(Column.kt:31)
	at org.jetbrains.exposed.sql.Query$prepareSQL$$inlined$buildString$lambda$1.invoke(Query.kt:156)
	at org.jetbrains.exposed.sql.Query$prepareSQL$$inlined$buildString$lambda$1.invoke(Query.kt:82)
	at kotlin.text.StringsKt__StringBuilderKt.appendElement(StringBuilder.kt:58)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:2195)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:2212)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:2211)
	at org.jetbrains.exposed.sql.Query.prepareSQL(Query.kt:156)
	at org.jetbrains.exposed.sql.Query.arguments(Query.kt:140)
	at org.jetbrains.exposed.sql.Query.arguments(Query.kt:82)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:32)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:128)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:122)
	at org.jetbrains.exposed.sql.Query.iterator(Query.kt:285)
	at com.ua.ecwo.repos.IKTRepoImpl_asSample$listAll$2.invoke(IKTRepoImpl.kt:53)
	at com.ua.ecwo.repos.IKTRepoImpl_asSample$listAll$2.invoke(IKTRepoImpl.kt:8)
	at com.ua.ecwo.repos.DatabaseFactory$dbQuery$2$1.invoke(DatabaseFactory.kt:56)
	at com.ua.ecwo.repos.DatabaseFactory$dbQuery$2$1.invoke(DatabaseFactory.kt:14)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:103)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:74)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:59)
	at com.ua.ecwo.repos.DatabaseFactory$dbQuery$2.doResume(DatabaseFactory.kt:52)

**Comment by student2ua** [comment]
https://stackoverflow.com/questions/9156379/ora-01882-timezone-region-not-found
JAVA_OPTS=-Doracle.jdbc.timezoneAsRegion=false
JAVA_OPTS=%JAVA_OPTS% -Duser.timezone=EET
